version: '2.1'

services:
  web:
    build: .
    volumes:
      - .:/app

  web_migrate:
    extends:
      service: web
    command: python3 manage.py migrate

  web_run:
    extends:
      service: web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"