version: '3.7'

services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  users_fe:
    build: ./users_fe
    command: ["npm", "start"]
    volumes:
      - ./users_fe:/app/users_fe
      - node_modules:/app/users_fe/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules: